### ISSUE TITLE
Failed to resolve: com.nineoldandroids:library:2.4.0+

### ISSUE THREAD

**Issue by sudarshaana** [konifar/fab-transformation#9]
I am using 
compile 'konifar:fab-transformation:1.0.0'
But suddenly it is showing "Failed to resolve: com.nineoldandroids:library:2.4.0+"

As konifar:fab-transformation:1.0.0 is using "com.nineoldandroids:library:2.4.0+" ; what to do now?

**Comment by waj0** [comment]
Changing '2.4.0+' to '2.4.0' in [build.gradle:84](https://github.com/konifar/fab-transformation/blob/master/fab-transformation/build.gradle#L84) will help. You can build library with this change by yourself and [add](http://stackoverflow.com/questions/24506648/adding-local-aar-files-to-gradle-build-using-flatdirs-is-not-working/28816265#28816265) to your app, if you can't wait for official release. I just did it myself :-)

[source](https://github.com/JakeWharton/NineOldAndroids/issues/88)

**Comment by sudarshaana** [comment]
I didn't use "com.nineoldandroids:library:2.4.0+". So where to change '2.4.0+' to '2.4.0'?

**Comment by iballan** [comment]
@sudarshaana he is talking about the library's dependencies. you have to download the library code and recompile it yourself

**Comment by iballan** [comment]
BTW, I got the same problem after i upgraded my Android Studio

**Comment by iballan** [comment]
@konifar 
I got the solution: Excluding nineoldandroids from the project, and add it to your project like this

```
compile 'com.nineoldandroids:library:2.4.0'
compile ('konifar:fab-transformation:1.0.0') {
        exclude group: 'com.nineoldandroids', module: 'library'
}
```

worked for me

**Comment by sudarshaana** [comment]
@iballan 
Thanks.
Thats also works for me.

**Comment by rsv355** [comment]
Thank's alot buddy....
Works for me as well

**Comment by iballan** [comment]
you are all welcome :)
